[package]
name = "logistic_map_rust"
version = "0.1.0"
authors = ["Susumu Yamazaki <zacky1972@gmail.com>"]

[dependencies]
time = "0.1.40"
ocl = "0.18"
ocl-extras = "0.1"

[profile.release]
opt-level = 3
codegen-units = 1
