[package]
name = "logistic_map_rust"
version = "0.1.0"
authors = ["Susumu Yamazaki <zacky1972@gmail.com>"]

[dependencies]
time = "0.1.40"
rayon = "1.0"
scoped-pool = "*"
lazy_static = "0.2"
num_cpus = "1.0"
ocl = "0.18"
ocl-extras = "0.1"

[profile.release]
opt-level = 3
codegen-units = 1
